  SELECT [Tran Type]
      ,[Tran Descript]
      ,[EE Name]
      ,[EE Number]
      ,[Start Trans Datetime]
      ,[End Trans Datetime]
      ,[Supervisor Name]
      ,[Department]
      ,[Warehouse #]
      ,[Date]
      ,[Transaction Qty]
      ,[WorkDay] AS [work_day]
      ,[Start Tran Date] AS [start_tran_date] 
      ,[Start Tran Time] AS [start_tran_time] 
      ,[End Tran Date] AS [end_tran_date]
      ,[End Tran Time] AS [end_tran_time]
      ,[COUNT]
      ,[GapTime] AS [Gap_Time]
      ,[ElapsedTime] AS [Elapsed_Time]
      ,[WorkTypeKey]
  FROM [PowerBI_Distribution].[GapTimeReport_EmployeeDetail]
  where [Warehouse #] IN ('335','35')
    and [EE Number] = '50290'