table Dim_code_table
	lineageTag: fffe722c-f196-4a8c-872d-41edc9d9f56d

	column Category
		dataType: string
		lineageTag: 3d3aa14f-fd7e-4375-9272-94a8392ca13d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Controllable_Code
		dataType: string
		lineageTag: f2344294-ccab-481c-98a7-3002d2202092
		summarizeBy: none
		sourceColumn: Controllable_Code

		annotation SummarizationSetBy = Automatic

	column Code_Description
		dataType: string
		lineageTag: 284c5f2e-1b01-483a-8eb5-fed71f2ac5de
		summarizeBy: none
		sourceColumn: Code_Description

		annotation SummarizationSetBy = Automatic

	partition Dim_code_table = m
		mode: import
		source = ```
				let
				    // 连接到 SharePoint 文件
				    Source = SharePoint.Files("https://masterashley.sharepoint.com/sites/AsiaWarehouseOperations/", [ApiVersion = 15]),
				    
				    // 筛选指定文件夹及其子文件夹下的文件
				    #"Filtered Folder" = Table.SelectRows(Source, each Text.StartsWith([Folder Path], "https://masterashley.sharepoint.com/sites/AsiaWarehouseOperations/Shared Documents/Ashton/Four Box/Shipping/bo_reason_code/")),
				    
				    // 仅筛选 .xlsx 文件
				    #"Excel Files Only" = Table.SelectRows( #"Filtered Folder", each Text.EndsWith([Name], ".xlsx")),
				    #"Filtered Rows" = Table.SelectRows(#"Excel Files Only", each ([Name] = "bo_reason_codes.xlsx")),
				    // 展开二进制内容
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Excel Tables", each Excel.Workbook([Content])),
				    
				    // 展开 Excel 表格
				    #"Expanded Excel Tables" = Table.ExpandTableColumn(#"Added Custom", "Excel Tables", {"Data", "Item", "Kind", "Hidden"}, {"Data", "Item", "Kind", "Hidden"}),
				    
				    // 仅保留名为 "DATA" 的工作表
				    #"Filtered Sheets" = Table.SelectRows(#"Expanded Excel Tables", each [Item] = "Sheet1"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Sheets",{"Data"}),
				    #"Expanded Data" = Table.ExpandTableColumn(#"Removed Other Columns", "Data", {"Column1", "Column2", "Column3"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Expanded Data", [PromoteAllScalars=true])
				in
				    #"Promoted Headers"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

