table fct_wanek_demand
	lineageTag: f8fde147-6deb-4adc-bfa8-7ca65e081b2a

	column wh_id
		dataType: string
		lineageTag: 71dadf2d-3013-47a1-b3f6-866931cf332b
		summarizeBy: none
		sourceColumn: wh_id

		annotation SummarizationSetBy = Automatic

	column order_number
		dataType: string
		lineageTag: 0c6563c6-2634-403b-94f9-1c230de2e3ad
		summarizeBy: none
		sourceColumn: order_number

		annotation SummarizationSetBy = Automatic

	column line_number
		dataType: int64
		formatString: 0
		lineageTag: 17e05391-b771-4c21-9d5c-85fbb771959c
		summarizeBy: sum
		sourceColumn: line_number

		annotation SummarizationSetBy = Automatic

	column item_number
		dataType: string
		lineageTag: 18a93437-9312-4acb-bcd8-d65fc36e669e
		summarizeBy: none
		sourceColumn: item_number

		annotation SummarizationSetBy = Automatic

	column pick_put_id
		dataType: string
		lineageTag: 6677c1a8-dc3d-4344-b4e7-c9f5e23de3d0
		summarizeBy: none
		sourceColumn: pick_put_id

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: e7d04ae0-986f-4ef0-b1c3-6cccfb8b14a7
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column qty
		dataType: double
		lineageTag: ee249a2d-dcdb-46f3-9df5-0c40f405076c
		summarizeBy: sum
		sourceColumn: qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qty_shipped
		dataType: double
		lineageTag: a54ee32f-df67-4938-8625-21e78bc9194f
		summarizeBy: sum
		sourceColumn: qty_shipped

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column diff_qty
		dataType: double
		lineageTag: 0d66a744-7e53-43ed-91bf-da8af618762e
		summarizeBy: sum
		sourceColumn: diff_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column staged_qty
		dataType: double
		lineageTag: c5921d77-7feb-40ee-9d91-b8d9c1439c23
		summarizeBy: sum
		sourceColumn: staged_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column loaded_qty
		dataType: double
		lineageTag: 78c31d4e-c5ca-4d26-8200-fff952f983d4
		summarizeBy: sum
		sourceColumn: loaded_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column load_id
		dataType: string
		lineageTag: e61ae943-64d6-4fb9-9e86-cba3c4c35f33
		summarizeBy: none
		sourceColumn: load_id

		annotation SummarizationSetBy = Automatic

	column transfer_whse_name
		dataType: string
		lineageTag: 66c7b401-cf22-44cc-b335-225380ebe9de
		summarizeBy: none
		sourceColumn: transfer_whse_name

		annotation SummarizationSetBy = Automatic

	column arrive_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a9916132-4860-4206-92fa-eaf2c59e72ab
		summarizeBy: none
		sourceColumn: arrive_date

		variation Variation
			isDefault
			relationship: 7bf04823-4b91-4d4c-8b4e-c5fc7291d646
			defaultHierarchy: LocalDateTable_5754a314-20b0-43e8-b877-da1728e89bea.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column unit_cube
		dataType: double
		lineageTag: 0d332915-8b87-43d0-9144-4a4b28cac833
		summarizeBy: sum
		sourceColumn: unit_cube

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cube
		dataType: double
		lineageTag: 5376f420-b0b1-4667-9eb1-ffdcbaa20bc5
		summarizeBy: sum
		sourceColumn: cube

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column storage
		dataType: double
		lineageTag: a811d747-0289-4ada-aa50-638ccd64f5d4
		summarizeBy: sum
		sourceColumn: storage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column open_allocation
		dataType: int64
		formatString: 0
		lineageTag: f8bf5250-a0de-4afb-9d85-b7c280d4c5b0
		summarizeBy: sum
		sourceColumn: open_allocation

		annotation SummarizationSetBy = Automatic

	column open_co
		dataType: double
		lineageTag: 4fec67c9-a15d-4dc0-b4dc-5cbb24b74754
		summarizeBy: sum
		sourceColumn: open_co

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fct_wanek_demand = m
		mode: import
		source =
				let
				    Source = Sql.Database("WanekWHJSQLprod", "AAD", [Query="-- =============================================#(lf)-- 1. 定义查询条件 (Define Query Parameters Here)#(lf)-- =============================================#(lf)DECLARE @Wh_Id TABLE (wh_id VARCHAR(50));#(lf)INSERT INTO @Wh_Id VALUES ('35'), ('31'), ('33'), ('36');#(lf)#(lf)DECLARE @Load_Id VARCHAR(50)      = '%';#(lf)DECLARE @Order_Number VARCHAR(50) = '%';#(lf)#(lf)-- =============================================#(lf)-- 2. 主查询 (Main Query)#(lf)-- =============================================#(lf)SELECT * FROM (#(lf)    SELECT #(lf)        orm.wh_id,#(lf)        orm.order_number,#(lf)        ord.line_number,#(lf)        ord.item_number,#(lf)        itm.pick_put_id,#(lf)        orm.status,#(lf)        ord.qty,#(lf)        ord.qty_shipped,#(lf)        (ord.qty - ord.qty_shipped) AS diff_qty,#(lf)        #(lf)        -- 暂存数量 (Staged Qty)#(lf)        (SELECT SUM(sto1.actual_qty) #(lf)         FROM t_stored_item sto1 WITH (NOLOCK) #(lf)         WHERE sto1.wh_id = ord.wh_id #(lf)           AND sto1.item_number = ord.item_number #(lf)           AND sto1.type = ord.order_number #(lf)           AND sto1.location_id IN (SELECT location_id FROM t_location WITH (NOLOCK) WHERE type = 'S')#(lf)        ) AS staged_qty,#(lf)        #(lf)        -- 装车数量 (Loaded Qty)#(lf)        (SELECT SUM(sto2.actual_qty) #(lf)         FROM t_stored_item sto2 WITH (NOLOCK) #(lf)         WHERE sto2.wh_id = ord.wh_id #(lf)           AND sto2.item_number = ord.item_number #(lf)           AND sto2.type = ord.order_number #(lf)           AND sto2.location_id IN (SELECT location_id FROM t_location WITH (NOLOCK) WHERE type = 'D')#(lf)        ) AS loaded_qty,#(lf)#(lf)        -- open_co = qty - qty_shipped - staged_qty - loaded_qty#(lf)        (#(lf)            ord.qty #(lf)            - ord.qty_shipped#(lf)            - ISNULL((SELECT SUM(sto1.actual_qty) #(lf)                      FROM t_stored_item sto1 WITH (NOLOCK) #(lf)                      WHERE sto1.wh_id = ord.wh_id #(lf)                        AND sto1.item_number = ord.item_number #(lf)                        AND sto1.type = ord.order_number #(lf)                        AND sto1.location_id IN (SELECT location_id FROM t_location WITH (NOLOCK) WHERE type = 'S')#(lf)                     ), 0)#(lf)            - ISNULL((SELECT SUM(sto2.actual_qty) #(lf)                      FROM t_stored_item sto2 WITH (NOLOCK) #(lf)                      WHERE sto2.wh_id = ord.wh_id #(lf)                        AND sto2.item_number = ord.item_number #(lf)                        AND sto2.type = ord.order_number #(lf)                        AND sto2.location_id IN (SELECT location_id FROM t_location WITH (NOLOCK) WHERE type = 'D')#(lf)                     ), 0)#(lf)        ) AS open_co,#(lf)        #(lf)        orm.load_id,#(lf)        tlk.transfer_whse_name,#(lf)        orm.arrive_date,#(lf)#(lf)        ROUND(ISNULL(itm.nested_volume, itm.unit_volume), 2) AS unit_cube,#(lf)        ROUND((ISNULL(itm.nested_volume, itm.unit_volume) * (ord.qty - ord.qty_shipped)), 2) AS cube,#(lf)        #(lf)        -- 存储数量 (Storage Qty)#(lf)        (SELECT SUM(actual_qty)  #(lf)         FROM t_stored_item sto WITH (NOLOCK) #(lf)         WHERE sto.wh_id = ord.wh_id#(lf)           AND sto.item_number = ord.item_number#(lf)           AND sto.status = 'A'#(lf)           AND sto.type = 'STORAGE'#(lf)           AND sto.location_id IN (SELECT location_id FROM t_location WITH (NOLOCK) WHERE type IN ('A','M','I','X','P'))#(lf)         GROUP BY sto.wh_id, sto.item_number#(lf)        ) AS storage,#(lf)        #(lf)        -- 开放分配数量 (Open Allocation)#(lf)        (SELECT allocation_qty - allocated_qty #(lf)         FROM t_soft_allocate_hotload allo WITH (NOLOCK) #(lf)         WHERE allo.wh_id = orm.wh_id#(lf)           AND allo.item_number = ord.item_number#(lf)           AND allo.load_id = orm.load_id#(lf)        ) AS open_allocation#(lf)#(lf)    FROM t_order orm WITH (NOLOCK) #(lf)    JOIN t_order_detail ord WITH (NOLOCK) #(lf)      ON orm.order_number = ord.order_number #(lf)     AND orm.wh_id = ord.wh_id#(lf)    JOIN t_lookup lok WITH (NOLOCK) #(lf)      ON orm.type_id = lok.lookup_id #(lf)     AND orm.wh_id = lok.wh_id #(lf)     AND lok.locale_id = '1033'#(lf)    JOIN t_item_master itm WITH (NOLOCK) #(lf)      ON ord.wh_id = itm.wh_id #(lf)     AND ord.item_number = itm.item_number#(lf)    LEFT JOIN (#(lf)        SELECT#(lf)            orm2.wh_id,#(lf)            orm2.order_number,#(lf)            orm2.load_id                                                        AS ad2055_load_id,#(lf)            (ISNULL(tlk2.description, '') + '(' + orm2.load_id + ')')          AS transfer_whse_name#(lf)        FROM dbo.t_order orm2 WITH (NOLOCK)#(lf)        JOIN dbo.t_lookup lok2 WITH (NOLOCK)#(lf)            ON  orm2.type_id   = lok2.lookup_id#(lf)            AND orm2.wh_id     = lok2.wh_id#(lf)            AND lok2.source    = 't_order'#(lf)            AND lok2.text      = 'HotLoad Orders'#(lf)            AND lok2.locale_id = '1033'#(lf)        LEFT JOIN dbo.t_lookup tlk2 WITH (NOLOCK)#(lf)            ON  orm2.load_id      = tlk2.text#(lf)            AND orm2.wh_id        = tlk2.wh_id#(lf)            AND tlk2.source       = 't_load_master'#(lf)            AND tlk2.lookup_type  = 'TRSFWHID'#(lf)            AND tlk2.locale_id    = '1033'#(lf)        WHERE orm2.wh_id IN (SELECT wh_id FROM @Wh_Id)#(lf)    ) tlk#(lf)      ON  tlk.wh_id        = orm.wh_id#(lf)      AND tlk.order_number = orm.order_number#(lf)#(lf)    WHERE 1=1#(lf)      AND orm.wh_id  IN (SELECT wh_id FROM @Wh_Id) #(lf)      AND orm.load_id LIKE @Load_Id #(lf)      AND orm.order_number LIKE @Order_Number#(lf)      AND lok.source = 't_order' #(lf)      AND lok.text = 'HotLoad Orders' #(lf)      AND orm.status NOT IN ('X','S','C')#(lf)#(lf)) AS sub#(lf)WHERE sub.open_co > 0#(lf)ORDER BY #(lf)    sub.order_number,#(lf)    sub.item_number;", CreateNavigationProperties=false, CommandTimeout=#duration(0, 8, 20, 0)]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"line_number", Int64.Type}, {"arrive_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

